# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock

baseurl: "https://pfe-2020-eseo.github.io/pfe.github.io/"
url: ""

# Custom vars
current_version:  2
docs_version:     2

